### PR TITLE
add additionalLabels to metrics

### PR DESCRIPTION
**Pull request by halleystar**
support
  additionalLabels:
    name1=value1
    name2=${labels:app}
    name3=prefix_${labels:owner}_suffix

### CODE REVIEW

**Comment by BSWANG** [comment]
please squash your commits

**Comment by halleystar** [comment]
finished

**Comment by halleystar** [comment]
done

**Comment by halleystar** [comment]
done

**Comment by BSWANG** [comment]
need rebase the origin main branch, there are unrelated commits in PR 
image

**Pull request closed without merging**
